### PR TITLE
Convert ND-TIFF position label

### PR DESCRIPTION
**Pull request by ziw-liu**
Convert non-HCS string-valued ND-TIFF position coordinate into column names of an HCS OME-Zarr store.

### CODE REVIEW

**Comment by ziw-liu** [comment]
@ieivanov The test v3 dataset does not have channel names. Is this intentional or an NDTiffStorage bug?

**Comment by ieivanov** [comment]
`ndtiff_v3_labeled_positions` only has a position dimension, no channels and therefore no channel names

**Comment by ieivanov** [comment]
@ziw-liu can you please test on `cm.automaton/mantis_HCS_acq_1` and debug? I am getting a `ValueError: Image coordinate channel = 1 is not part of this dataset.` error. The string axis parsing needs to be extended to the channel dimension as well.

**Comment by ziw-liu** [comment]
> @ziw-liu can you please test on `cm.automaton/mantis_HCS_acq_1` and debug? I am getting a `ValueError: Image coordinate channel = 1 is not part of this dataset.` error. The string axis parsing needs to be extended to the channel dimension as well.

@ieivanov I can now convert those datasets. Can you review again?

**Review by ieivanov — APPROVED** [review]
I think this is good for now. Thanks a lot!

When you're working on the readers next, you can consider moving `_normalize_ndtiff_coord` to the reader to simplify `_check_coordinates` and the metadata fetching during init which still uses integer indices.

**Pull request merged**
