### PR TITLE
Unified API for Micro-manager readers

### PR DESCRIPTION
**Pull request by ieivanov**

### CODE REVIEW

**Comment by ieivanov** [comment]
@ziw-liu @JoOkuma I have been using the new readers and I think they work well. This summer we have plans for acquiring a lot of data and I would like to distribute the work of converting and reconstructing data by training a wider set of users (see draft of https://czbiohub.atlassian.net/wiki/x/GgBKw). It's important that we use this version of the code for data conversion to avoid millions of small files. It'll be helpful if we merge this branch into main now rather than waiting to convert the zarr file type to the universal API format as well. Do you see any setbacks?

**Comment by ziw-liu** [comment]
> It'll be helpful if we merge this branch into main now rather than waiting to convert the zarr file type to the universal API format as well. Do you see any setbacks?

I don't see major issues in this plan. I will handle conflicts and open separate PRs to fix documentation before merging this.

**Comment by ziw-liu** [comment]
For history granularity reasons, I suggest avoid pushing to this branch directly and use a merge commit to main.

**Comment by ziw-liu** [comment]
> For history granularity reasons, I suggest avoid pushing to this branch directly and use a merge commit to main.

See #223

**Comment by ziw-liu** [comment]
Linking issues slated for closing in #185.

**Comment by ziw-liu** [comment]
@JoOkuma In my view this PR does not meet the v0.2 milestone. Is there a specific use case for an immediate release after merging?

**Review by ziw-liu — APPROVED** [review]

**Pull request merged**
